Implemented sparse-checkouts and enhanced the CLI experience
zikani03/git-down pull request #1
Opened 2022-04-09 19:07 UTC by kwalter94

- Replaced use of `git clone` with `git sparse-checkout` to minimise download sizes (CAVEAT: users are now supposed to specify a branch to checkout from)
- Added a nicer CLI that provides some basic help text
```sh
git-down -d gh:zikani03/git-down:master src Cargo.toml

git-down --help
```
- Made specifying of download directory optional
- Enabled downloading of specific files not just directories
- Major refactor of the codebase

NOTE: Project seems to be missing a LICENSE.

2022-04-12 23:01 UTC, zikani03 requested changes
Thanks for the contributions! 
Just a couple of requests. 
Overall this is *much much much*  better code than what was there before 👍🏾

2022-04-12 23:01 UTC, zikani03 commented on Cargo.toml
>  authors = ["Zikani Nyirenda Mwase <zikani.nmwase@ymail.com>"]
@kwalter94 Add your details to authors :)

2022-04-12 23:01 UTC, zikani03 commented on src/git.rs
> +            let path = self.local_dir.path();
Can this be moved outside the loop?

2022-04-12 23:01 UTC, zikani03 commented on src/git.rs
> +fn git_init(git_dir: &GitDir) -> Result<(), GitDownError> {
Very minor nit pick (feel free to ignore)😅  but can this function be renamed? Took a couple of minutes to realize this runs the whole git workflow instead of just "git init".

2022-04-13 06:18 UTC, kwalter94 commented on src/git.rs
> +fn git_init(git_dir: &GitDir) -> Result<(), GitDownError> {
Good catch, actually that function isn't even necessary. That logic should be moved to the function that calls it (ie git::sparse_checkout).

2022-04-13 06:29 UTC, kwalter94 commented
Have made the changes you requested, anything else?

2022-04-13 13:36 UTC, zikani03 commented
Awesome, looks great!

2022-04-13 13:36 UTC, merged